### ISSUE TITLE
Why Action1<? super Throwable> ? instead of Action1<Throwable>

### ISSUE THREAD

**Issue by baoti** [JakeWharton/NotRxAndroid#3]
Why not this method just return `Action1<Throwable>` ?
I don't understand it, can anybody explain it for me? Thanks!
<https://github.com/JakeWharton/NotRxAndroid/blob/5c0ba7dff90aa69b936059d6c35e6c2b23370900/rxandroid/src/main/java/rx/android/util/RxLog.java#L55>
```
  public static Action1<? super Throwable> error(final String tag, final String message) {
    checkNotNull(tag, "tag == null");
    checkNotNull(message, "message == null");

    final RxAndroidLogHook logHook = RxAndroidPlugins.getInstance().getLogHook();
    return new Action1<Throwable>() {
      @Override public void call(Throwable throwable) {
        logHook.log(Log.ERROR, tag, message, throwable);
      }
    };
  }
```

**Comment by JakeWharton** [comment]
Probably got a little too copy/paste happy. #5 will end up fixing this.
