### ISSUE TITLE
"Generic" View Actions?

### ISSUE THREAD

**Issue by curioustechizen** [JakeWharton/NotRxAndroid#30]
I am sure this has been discussed in the past, but I could not find any reference to it. The proposal is to provide a way for "generic" Actions to be so that any custom `View` is already Rx-ready as long as it follows certain naming conventions. I have in mind something along the lines of:

```java
 /**
   * An action which sets the specified property of {@code view}. The View is expected to have a setter of the form set[propertyName] in camel-case.
   * <p>
   * <em>Warning:</em> The created observable keeps a strong reference to {@code view}. Unsubscribe
   * to free this reference.
   */
  public static Action1<?> property(final View view, final String prop) {
    checkNotNull(view, "view == null");
    return new Action1<Object>() {
      @Override public void call(Object value) {
        final Method method = view.getClass().getDeclaredMethod(Utils.getMethodNameForProperty(prop), new Class[]{value.getClass()});
        method.invoke(view, value);
      }
    };
  }
```

Some observations about this in no particular order:

  - A useful way to bind any property of any custom `View` to some value
  - Roughly comparable to utilities available in ReactiveCocoa (example - `RAC()` macro) although the language capabilities are a whole lot different in these two cases
  - Reflection! Ugly, not type-safe.
  - That requirement about having a setter for the property - again not pretty ... ...
  - ... ... but, you probably already follow it if you are using the Property Animation framework (does this use reflection too BTW?Just curious)

**Comment by JakeWharton** [comment]
Very hesitant about using reflection. You lose compile-time safety and introduce overhead whereas the library now is very low overhead (close to no overhead).

> you probably already follow it if you are using the Property Animation framework (does this use reflection too BTW?Just curious

No. It's parameterized over a type (e.g., `Integer`) and then offers `T get()` and `set(T value)` methods.

**Comment by JakeWharton** [comment]
Actually, it depends on that last point. You can either use `Property`-based properties which are reflection free, or it'll fall back to either using jni to cache method handles and invoke as a faster reflection or finally do normal Java-based reflection.

**Comment by curioustechizen** [comment]
>Very hesitant about using reflection.

Fair enough.

>it'll fall back to either using jni to cache method handles and invoke as a faster reflection or finally do normal Java-based reflection.

Ah I see. JNI. I guessed there had to be some way to avoid invoking a method through reflection at every frame!

Thanks for the explanation. Do you want to keep this thread open for more opinions? Or should I close it?

**Comment by JakeWharton** [comment]
I'm going to close it because it's easy to implement this yourself if you wanted the reflection-based version of this. For a library, though, I'd like to retain the safety of the methods.
