### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by westito** [JakeWharton/NotRxAndroid#31]
Can you share some sample to this library?

**Comment by JakeWharton** [comment]
No. Samples will be created when the code is upstreamed into RxAndroid.

**Comment by JakeWharton** [comment]
The usage of the individual APIs is simple, see the tests for that. You'll have to use your imagination on how to compose the operators together to form something complex.

**Comment by pakoito** [comment]
Are you 100% positive the code will be upstreamed into RxAndroid?

**Comment by JakeWharton** [comment]
I have commit rights to RxAndroid. So yes.

**Comment by pentarex** [comment]
Are you sure? I mean I really see nice examples with your library, but always too old, and I am using kotlin. So maybe sometimes when/if you or some other have time to make examples for us the newbies it will be great. Thanks. Keep up with the good work!

**Comment by JakeWharton** [comment]
The comments were for a different library than RxBinding at the time.
