### ISSUE TITLE
RxDialog oneliners

### ISSUE THREAD

**Issue by pakoito** [JakeWharton/NotRxAndroid#32]
For your Q&D needs, it is possible to spin an observable dialog in a single line. This is helpful to quickly create a picker for yes/no, date, number, decimal or single element in a list. i.e. button click flatmap into confirmation dialog flatmap into execute action.

Is that within scope of this library, or as a helper would it live outside?

**Comment by dlew** [comment]
My two cents: out of scope for this library.

To me, it seems like a fairly large task to make a proper Rx dialog library. There's a lot of depth to dialogs, if you're dealing with them in a general sense, since you can do just about anything with them - they're just floating windows.

**Comment by pakoito** [comment]
Okay, assume my pitch is out and I put my weekends on another library. What does a proper stock Rx dialog library need? Listeners for each of the mentioned types, styling is still done at theme level, anything else? Those two I've already covered before.

**Comment by dlew** [comment]
I do so many crazy things with dialogs that I don't think a library could ever cover all the use cases. E.g., some dialogs have custom layouts inside of them which have lots of logic/control outside the bounds of any normal dialog listener.

If I were to make a library I'd make it tightly focused on some very common use cases, such as displaying a title/message/buttons. Once you start expanding beyond that (into things like adapters and custom views) it gets a lot more complex.

**Comment by pakoito** [comment]
Yes, if you want the custom ones. I was thinking something more stock for those cases, with stock UI components like a simple picker. Without styling and only allowing changes to title, message and elements/boundaries, most of them are trivial to wire.

http://developer.android.com/images/ui/dialogs.png

http://developer.android.com/images/ui/dialogs_regions.png

http://developer.android.com/images/ui/dialog_checkboxes.png

http://developer.android.com/images/ui/dialog_custom.png

http://developer.android.com/images/ui/pickers.png

http://i.stack.imgur.com/k5xNW.png
