### ISSUE TITLE
Rename HandlerSchedulers into AndroidSchedulers?

### ISSUE THREAD

**Issue by artem-zinnatullin** [JakeWharton/NotRxAndroid#36]
Probably, `AndroidSchedulers` is better name for factory of Rx Schedulers for Android App than `HandlerSchedulers`. Yes, internally these Schedulers use `Handler` but it's just an implementation detail. 

Also, `AndroidSchedulers` is already well known ~~brand~~ class by RxAndroid community, users and even those who don't use RxAndroid, but has seen tons of examples in the internet, so new API won't be so "breaking" for them (I won't be surprised if most of RxAndroid users use only schedulers).

**Comment by JakeWharton** [comment]
This repository will never have releases and is not competing for RxAndroid users so the name that library uses and the articles written about it are completely meaningless and irrelevant to what goes on here.

Ultimately, however, I don't agree. The class is a factory for schedulers from a handler. The means of operating on the main thread is only done through a handler.
